version: 2
jobs:
  tox:
      docker:
        - image: circleci/python:3.7

      steps:
        - checkout
        - run: pip install tox && tox

workflows:
  version: 2
  build_and_test:
    jobs:
      - tox